// fe_trivia_cra/src/container/main/auth/components/SignUp.jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import * as authActions from '../actions/authActions';
import { connect } from 'react-redux';
import { Redirect } from 'react-router-dom';
import { validUserSignUpData, checkValidRole, giveAdmin } from '../../../../services/userValidationService';
import globalConstants from '../../../../resources/globalConstants';
import '../styles/signup.css';

class SignUp extends Component {
    constructor(props) {
        super(props);
        this.state = {};
        this.handleSignUp = this.handleSignUp.bind(this);
    }

    handleSignUp(event) {
        event.preventDefault();
        const username = event.target.username.value;
        const passcode = event.target.passcode.value;
        const passcodeConfirm = event.target.passcodeConfirm.value;
        let roleCheck = event.target.role.value;
        let role = 'USER';

        const dataWithConfirm = {
            passcode,
            passcodeConfirm,
            username
        };

        // Validate data
        const inputErrors = validUserSignUpData(dataWithConfirm);

        if (checkValidRole(roleCheck)) {
            if (giveAdmin(roleCheck)) {
                role = 'ADMIN';
            } else {
                inputErrors.push('Invalid permissions, please leave blank');
            }
        }

        const signUpData = {
            passcode,
            role,
            username
        };

        if (inputErrors.length === 0) {
            this.props.dispatch(authActions.handleLogin(signUpData));
        } else {
            this.props.dispatch(authActions.throwAuthErrors(inputErrors));
        }
    }

    componentDidMount() {
        this.props.dispatch(authActions.throwAuthErrors([]));
    }

    // Pull in auth error state
    getAuthErrors() {
        return this.props.authState.authErrors;
    }

    // Clear errors and disable submit button
    componentWillUnmount() {
        this.props.dispatch(authActions.throwAuthErrors([]));
        this.props.dispatch(authActions.validLogin(false));
    }

    render() {
        const authErrors = this.getAuthErrors(); // get auth errors from state

        if (sessionStorage.getItem(globalConstants.tokenKey)) {
            return <Redirect to="/" />;
        } else {
            return (
                <div className="container">
                    <div className="signup-card">
                        <form onSubmit={this.handleSignUp}>
                            <h2 className="heading">Sign Up</h2>

                            <label htmlFor="username" className="label">
                Username
                            </label>
                            <input
                                type="username"
                                name="username"
                                className="form-input"
                                maxLength="12"
                                placeholder="Please enter your preferred username"
                                required
                            />

                            <label htmlFor="passcode" className="label">
                Passcode
                            </label>
                            <input
                                type="password"
                                name="passcode"
                                className="form-input"
                                placeholder="Choose a 3-6 digit passcode"
                                required
                            />

                            <input
                                type="password"
                                name="passcodeConfirm"
                                className="form-input"
                                placeholder="Confirm passcode"
                                required
                            />

                            <label htmlFor="role" className="label">
                Permissions
                            </label>
                            <input
                                type="password"
                                name="role"
                                className="form-input"
                                placeholder="May be left blank"
                                maxLength="12"
                            />

                            <button
                                type="submit"
                                className="btn btn-signup"
                            >
                Sign Up!
                            </button>
                        </form>
                    </div>
                    <div className="error-container">
                        <div className="errors">
                            {authErrors.map((err, i) => (
                                <p key={i}>{err}</p>
                            ))}
                        </div>
                    </div>
                </div>
            );
        }
    }
}

// Connect this class to application state
const mapStateToProps = state => {
    return {
        authState: state.authState
    };
};

// Validate prop types
SignUp.propTypes = {
    authState: PropTypes.object,
    dispatch: PropTypes.func.isRequired
};

export default connect(mapStateToProps)(SignUp);

// fe-trivia-ng/src/app/main/auth/signup/signup.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router } from '@angular/router';
import { UserService } from '../../services/user.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {
  username: string;
  passcode: number;
  passcodeConfirm: number;
  role: string;
  errorMessages: string[];

  constructor(private router: Router, private userService: UserService) {}

  ngOnInit() {}

  signUp(valid: boolean) {
    const username = this.username;
    const passcode = this.passcode;
    let role = this.role;
    let adminCreds = false;
    let goAhead = false;

    if (valid) {
      if (role !== undefined) {
        const adminReg = role.match('^midasmod$');
        if (role.length !== 0 && !adminReg) {
          this.errorMessages.push('Please leave the "Permissions" field blank');
          goAhead = false;
        } else if (adminReg) {
          adminCreds = true;
          goAhead = true;
        } else {
          goAhead = true;
          adminCreds = false;
          this.errorMessages = [];
        }
      } else {
        goAhead = true;
        adminCreds = false;
      }

      if (goAhead) {
        role = 'USER';
        if (adminCreds) {
          role = 'ADMIN';
        }
        const userObject = {
          passcode,
          role,
          username
        };
        this.userService.onCreateFetch(userObject)
        .subscribe(() => {
          this.errorMessages = [];
          this.loginAfterSignUp(userObject);

          // this.userService.passThrough(['Successful signup, please login']);
          // this.router.navigateByUrl('/');
        }, error => {
          if (error.status === 409) {
            this.errorMessages.push('This username is already taken');
          } else if (error.status === 400) {
            this.errorMessages.push('Incorrect data entered');
          } else if (error.status >= 500) {
            this.errorMessages.push('Server error');
            this.errorMessages.push('Please try again later');
          } else {
            this.errorMessages.push('Unknown error');
            this.errorMessages.push('Please contact a system administrator');
          }
        });
      }
    }
  }

  validateUser() {
    const validUsername = !!this.username.match('^[a-zA-Z]+$');
    const validPasscode = this.passcode > 99 && this.passcode < 1000000;
    const passcodeConfirmed = this.passcode === this.passcodeConfirm;
    const theyAreMe = this.username.toLowerCase().match('^billy$');
    let valid = false;
    const errArr = [];

    if (!validUsername) {
      errArr.push('Username must be letters only');
    }
    if (!validPasscode) {
      errArr.push('Passcode must be 3-6 digits long');
    }
    if (!passcodeConfirmed) {
      errArr.push('Passcode entries do not match');
    }
    if (theyAreMe) {
      errArr.push('Username is in use ._.');
    }

    if (errArr.length === 0) {
      valid = true;
      this.errorMessages = errArr;
      this.signUp(valid);
    } else {
      valid = false;
      this.errorMessages = errArr;
    }
  }
   loginAfterSignUp(userObject) {
    const errArr = [];
    userObject.role = 'LOGIN';

    this.userService.tryLogin(userObject)
     .subscribe(response => {
      this.userService.currentUser = response;
      this.router.navigateByUrl('/');
    }, error => {
      if (error.status === 404) {
        errArr.push('Username not found, please check username');
      } else if (error.status === 409) {
        errArr.push('Username or passcode is incorrect');
      } else if (error.status === 500) {
        errArr.push('Server error');
        errArr.push('Please try again later');
      } else if (error.status === 400) {
        errArr.push('Username or passcode is formatted incorrectly');
      } else {
        errArr.push('Unexpected error');
        errArr.push('Please contact administrator');
      }
      this.errorMessages = errArr;
    });
   }
}

<div class="container">
  <div class="signup-card">
    <form #signupForm="ngForm">
      <h2 class="heading">Sign Up</h2>

      <label for="username" class="label">Username</label>
      <input type="username" name="username" class="form-input" [(ngModel)]="username" maxlength="60"
        placeholder="Please enter your preferred username" required />

      <label for="passcode" class="label">Passcode</label>
      <input type="password" name="passcode" class="form-input" [(ngModel)]="passcode"
        placeholder="Choose a 3-6 digit passcode" required />

      <input type="password" name="passcode-confirm" class="form-input" [(ngModel)]="passcodeConfirm"
        placeholder="Confirm passcode" required />

      <label for="role" class="label">Permissions</label>
      <input type="password" name="role" class="form-input" [(ngModel)]="role" placeholder="May be left blank"
        maxlength="12" />

      <button [disabled]="!signupForm.form.valid" type="submit" (click)="validateUser()" class="btn btn-signup">
        Sign Up!
      </button>
    </form>
  </div>
  <div class="error-container">
    <div class="errors" *ngFor="let err of errorMessages">
      {{ err }}
    </div>
  </div>
</div>
