// fe-trivia-ng/src/app/main/quizzes/stroop-easy/stroop-easy.component.ts
import { Component, OnInit, HostListener } from '@angular/core';
import { LeaderboardService } from '../../services/leaderboard.service';
import { UserService } from '../../services/user.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-stroop-easy',
  templateUrl: './stroop-easy.component.html',
  styleUrls: ['./stroop-easy.component.css']
})
export class StroopEasyComponent implements OnInit {
  red = false;
  green = false;
  blue = false;
  yellow = false;
  redClass = false;
  greenClass = false;
  blueClass = false;
  yellowClass = false;
  answerFeedback: string;
  numOfCorrectAnswers = 0;
  numOfIncorrectAnswers = 0;
  testActive = false;
  testTimer: number;
  testResults = false;
  resultScreenMessage: string;
  errorMessage: any;

  constructor(
    private leaderboardService: LeaderboardService,
    private userService: UserService,
    private router: Router
  ) {}

  ngOnInit() {}

  goBack() {
    this.router.navigateByUrl('/');
  }

  randomizer(): number {
    return Math.floor(Math.random() * 4);
  }

  randomPick() {
    const pick = this.randomizer();
    const classPick = this.randomizer();

    this.setAllFalse();
    this.randomColorClass(classPick);
    this.randomColorWord(pick);
  }

  randomColorWord(pick: number) {
    switch (pick) {
      case 0:
        this.red = true;
        break;
      case 1:
        this.green = true;
        break;
      case 2:
        this.blue = true;
        break;
      case 3:
        this.yellow = true;
        break;
      default:
        break;
    }
  }

  randomColorClass(classPick: number) {
    switch (classPick) {
      case 0:
        this.redClass = true;
        break;
      case 1:
        this.greenClass = true;
        break;
      case 2:
        this.blueClass = true;
        break;
      case 3:
        this.yellowClass = true;
        break;
      default:
        break;
    }
  }

  setAllFalse() {
    this.red = false;
    this.blue = false;
    this.green = false;
    this.yellow = false;
    this.redClass = false;
    this.blueClass = false;
    this.greenClass = false;
    this.yellowClass = false;
  }

  beginTest() {
    if (!this.testActive) {
      this.beginTimer(30);
      this.randomPick();
    }
    this.testActive = true;
  }

  beginTimer(time: number) {
    this.testTimer = time;
    const newClock = setInterval(() => this.timerTick(newClock), 1000);
  }

  timerTick(newClock: any) {
    if (this.testTimer > 0) {
      this.testTimer--;
    } else {
      this.testComplete(newClock);
    }
  }

  @HostListener('document: keypress', ['$event'])
  handleAnswer(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      this.beginTest();
    }

    if (this.testActive) {
      if (this.numOfIncorrectAnswers > 9) {
        this.testTimer = 0;
      } else {
        switch (event.key) {
          case 'r':
            if (this.red) {
              this.correctAnswerChosen();
            } else {
              this.incorrectAnswerChosen();
            }
            this.randomPick();
            break;
          case 'g':
            if (this.green) {
              this.correctAnswerChosen();
            } else {
              this.incorrectAnswerChosen();
            }
            this.randomPick();
            break;
          case 'b':
            if (this.blue) {
              this.correctAnswerChosen();
            } else {
              this.incorrectAnswerChosen();
            }
            this.randomPick();
            break;
          case 'y':
            if (this.yellow) {
              this.correctAnswerChosen();
            } else {
              this.incorrectAnswerChosen();
            }
            this.randomPick();
            break;
          default:
            // nothing
            break;
        }
      }
    }
  }

  correctAnswerChosen() {
    this.answerFeedback = 'Correct!';
    this.numOfCorrectAnswers++;
  }

  incorrectAnswerChosen() {
    this.answerFeedback = 'Miss';
    this.numOfIncorrectAnswers++;
  }

  testComplete(newClock: any) {
    clearInterval(newClock);
    this.testActive = false;
    this.testResults = true;
    const correct = this.numOfCorrectAnswers;
    if (correct >= 0 && correct < 10) {
      this.resultScreenMessage = 'Good try!';
    } else if (correct >= 10 && correct < 20) {
      this.resultScreenMessage = 'Not bad!';
    } else if (correct >= 20 && correct < 30) {
      this.resultScreenMessage = 'Mad decent!';
    } else if (correct >= 30 && correct < 40) {
      this.resultScreenMessage = 'Great job!!';
    } else if (correct >= 40 && correct < 50) {
      this.resultScreenMessage = '♪ Most excellent ♪';
    } else if (correct >= 50 && correct < 60) {
      this.resultScreenMessage = 'Wicked!'; // easter eggs start here
    } else if (correct >= 60 && correct < 66) {
      this.resultScreenMessage = 'Blazing fast!';
    } else if (correct === 66) {
      this.resultScreenMessage = 'Hail satin!';
    } else {
      this.resultScreenMessage = 'Amazing!!';
    }

    const userId = this.userService.getUserId();

    if (userId != null) {
      const scoreObject = {
        quizScore: correct,
        user: {
          id: userId
        },
        quiz: 'Stroop Test - Easy'
      };
      this.leaderboardService.onCreateEntry(scoreObject).subscribe();
    } else {
      this.router.navigateByUrl('/login');
      alert('You are not logged in!');
    }
  }

  tryAgain() {
    this.testResults = false;
    this.answerFeedback = '';
    this.numOfCorrectAnswers = 0;
    this.numOfIncorrectAnswers = 0;
  }
}

<div *ngIf="testActive">
  Timer: {{ testTimer }}
</div>
<div class="stroop-container">
  <!-- Class is randomly generated, as is the word
    Word is used to determine correctness -->
  <div *ngIf="!testActive">
    <div class="splash-text" *ngIf="!testResults">
      Stroop Test - Easy
    </div>
  </div>
  <div *ngIf="testActive">
    <div *ngIf="red"
      [ngClass]="{'color-red':redClass, 'color-green':greenClass, 'color-blue':blueClass, 'color-yellow':yellowClass}">
      RED</div>
    <div *ngIf="green"
      [ngClass]="{'color-red':redClass, 'color-green':greenClass, 'color-blue':blueClass, 'color-yellow':yellowClass}">
      GREEN</div>
    <div *ngIf="blue"
      [ngClass]="{'color-red':redClass, 'color-green':greenClass, 'color-blue':blueClass, 'color-yellow':yellowClass}">
      BLUE</div>
    <div *ngIf="yellow"
      [ngClass]="{'color-red':redClass, 'color-green':greenClass, 'color-blue':blueClass, 'color-yellow':yellowClass}">
      YELLOW</div>
  </div>
  <div *ngIf="testResults" class="splash-text">
    {{ resultScreenMessage }}
  </div>
</div>
<div *ngIf="!testResults" class="info-panel">
  <div>
    <div *ngIf="!testActive" id="stroop-input">Press Enter to Begin!</div>
  </div>
  <div class="info" *ngIf="!testActive">
    - Don't miss more than ten!<br />
    - You have 30 seconds!<br />
    <hr />
  </div>
  <div class="controls">
    "R" for RED <br />
    "G" for GREEN <br />
    "B" for BLUE <br />
    "Y" for YELLOW
  </div>
  {{ answerFeedback }}
  <div *ngIf="testActive">
    Correct: {{ numOfCorrectAnswers }}
  </div>
</div>
<div *ngIf="testResults" class="test-results">
  <div>
    Congrats! <br />
    You scored {{ numOfCorrectAnswers }} correct answers in 30 seconds and missed {{ numOfIncorrectAnswers }}!
  </div>
  <div>
    <button type="button" (click)="tryAgain()">Try Again</button>
  </div>
  <div>
    {{ errorMessage }}
  </div>
</div>
<hr class="rule" />
<div>
  <button type="button" routerLink="/">Abandon Quiz</button>
</div>

// fe_trivia_cra/src/container/main/quizzes/components/StroopEasy.jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { Redirect } from 'react-router-dom';
import globalConstants from '../../../../resources/globalConstants';
import '../styles/stroop-easy.css';

class StroopEasy extends Component {
    constructor(props) {
        super(props);
        this.state = {  };
    }
    render() {
        if (!sessionStorage.getItem(globalConstants.tokenKey)) {
            return <Redirect to="/login" />;
        } else {
            return (
                <div>
                    <div>
  Timer: { 'testTimer' }
                    </div>
                    <div className="stroop-container">
                        {/* <!-- Class is randomly generated, as is the word
    Word is used to determine correctness --> */}
                        <div >
                            <div className="splash-text" >
      Stroop Test - Easy
                            </div>
                        </div>
                        <div>
                            <div>
      RED</div>
                            <div>
      GREEN</div>
                            <div >
      BLUE</div>
                            <div>
      YELLOW</div>
                        </div>
                        <div className="splash-text">
                            { 'resultScreenMessage' }
                        </div>
                    </div>
                    <div className="info-panel">
                        <div>
                            <div id="stroop-input">Press Enter to Begin!</div>
                        </div>
                        <div className="info">
    - Don&#39;t miss more than ten!<br />
    - You have 30 seconds!<br />
                            <hr />
                        </div>
                        <div className="controls">
    &quot;R&quot; for RED <br />
    &quot;G&quot; for GREEN <br />
    &quot;B&quot; for BLUE <br />
    &quot;Y&quot; for YELLOW
                        </div>
                        { 'answerFeedback' }
                        <div>
    Correct: { 'numOfCorrectAnswers' }
                        </div>
                    </div>
                    <div className="test-results">
                        <div>
    Congrats! <br />
    You scored { 'numOfCorrectAnswers' } correct answers in 30 seconds and missed { 'numOfIncorrectAnswers' }!
                        </div>
                        <div>
                            <button type="button" >Try Again</button>
                        </div>
                        <div>
                            { 'errorMessage' }
                        </div>
                    </div>
                    <hr className="rule" />
                    <div>
                        <button type="button" routerLink="/">Abandon Quiz</button>
                    </div>
                </div>
            );
        }
    }
}
 
// Connect this class to application state
const mapStateToProps = state => {
    return {
        authState: state.authState
    };
};

// Validate prop types
StroopEasy.propTypes = {
    dispatch: PropTypes.func.isRequired
};

export default connect(mapStateToProps)(StroopEasy);
