// fe-trivia-ng/src/app/main/feedback/patch-notes/patch-notes.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-patch-notes',
  templateUrl: './patch-notes.component.html',
  styleUrls: ['./patch-notes.component.css']
})
export class PatchNotesComponent implements OnInit {
  // Change routes to have children

  constructor() { }

  ngOnInit() {
  }

}

<div class="center">
  <!-- Patch Divider -->
  <div class="patch">
      Version 0.2.0:
      <ul class="patch-notes">
          <li>&#8810; Stroop Test - Insane &#8811; is now insane! Added random fonts and background</li>
          <li>Randomizer added</li>
          <li>Leaderboard prepopulates with dashes now</li>
      </ul>
    </div>
  <!-- Patch Divider -->
  <div class="patch">
    Version 0.1.0:
    <ul class="patch-notes">
      <li>Login and sign up implemented</li>
      <li>Authentication/authorization with page blocks in place</li>
      <li>Leaderboards for all implemented quizzes are active and will rank the top ten users' scores</li>
      <li>Added 'Log Out' button</li>
      <li>&#8810; Stroop Test - Easy &#8811; is online!</li>
      <li>&#8810; Stroop Test - Complex &#8811; is online!</li>
      <li>&#8810; Stroop Test - Insane &#8811; is online!</li>
    </ul>
  </div>
</div>

// fe_trivia_cra/src/container/main/administration/components/PatchNotes.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import '../styles/patch-notes.css';

const PatchNotes = () => {
    return (
        <span>
            <div className="center">
                {/* <!-- Patch Divider --> */}
                <div className="patch">
          Version 0.1.0:
                    <ul className="patch-notes">
                        <li>Login and sign up implemented</li>
                        <li>Authentication/authorization with page blocks in place</li>
                        <li>&#8810; Stroop Test - Easy &#8811; is online!</li>
                        <li>
              Leaderboards for all implemented quizzes are active and will rank
              the top ten users scores
                        </li>
                        <li>Added Log Out button</li>
                        <li>&#8810; Stroop Test - Complex &#8811; is online!</li>
                    </ul>
                </div>
            </div>
            <div className="center">
                <Link to="/"><button>Home</button></Link>
            </div>
        </span>
    );
};

export default PatchNotes;
